### ISSUE TITLE
Add property to store parameters on workflow bindings.

### ISSUE THREAD

**Issue by hvarg** [KnowledgeCaptureAndDiscovery/DISK-Ontologies#10]
We need to store a new type of workflow bindings: Parameters.
I'm using an object type property `:hasParameter` with domain WorkflowBinding and range VariableBinding.
We do not need a new type, as a parameter is a special case of WorkflowBinding

**Comment by dgarijo** [comment]
Addressed by https://github.com/KnowledgeCaptureAndDiscovery/DISK-Ontologies/pull/11
