### ISSUE TITLE
Add creationDate as property for Hypotheses, LOI and TLOI

### ISSUE THREAD

**Issue by hvarg** [KnowledgeCaptureAndDiscovery/DISK-Ontologies#2]
We need a property to store the creation date of hypotheses, LOI, and TLOI.

Something like `:creationDate` should work. Should accept some of these types: `xsd:dateTime`, `xsd:date` or `xsd:dateTimeStamp`

**Comment by boydjosh** [comment]
can the existing data property `:hasStartDate` be applied?

**Comment by hvarg** [comment]
Sounds good to me, but I was reading this file:
https://knowledgecaptureanddiscovery.github.io/DISK-Ontologies/disk/1.1.0/ontology.ttl 
and I don't see that property there. 
Where I can find it?

**Comment by boydjosh** [comment]
I saw it here `https://knowledgecaptureanddiscovery.github.io/EnigmaOntology/release/project/1.0.0/index-en.html#hasStartDate`

**Comment by hvarg** [comment]
Oh, is defined on Enigma but it does not show on the `.ttl` file of the last version:
https://knowledgecaptureanddiscovery.github.io/DISK-Ontologies/enigma_hypothesis/release/2.0.0/ontology.ttl

Anyways, as is a property for Hypotheses, LOI, and TLOI I think it should be defined on the DISK ontology. Any idea @dgarijo ?

**Comment by dgarijo** [comment]
Yes, we should create it in DISK under that namespace. @haripriyad252 can you please do it? we can call it `dateCreated`. It's different from `startDate` because `startDate` refers to the date when a working group starts. `dateCreated` refers to the creation date of a hypothesis.

**Comment by haripriyad252** [comment]
Sure, I can add it here: https://knowledgecaptureanddiscovery.github.io/DISK-Ontologies/enigma_hypothesis/release/2.0.0/ontology.ttl

Should I add it under object property?

**Comment by dgarijo** [comment]
@haripriyad252, no, please do the following:

-  In the /development folder, you should see `neuro.owl`. Update that file. Create the new property as a datatype property. Create another property dateModified to indicate when was a hypothesis modified. Add labels to both properties and add a description.
- Next, do a pull request and I will inspect. Thanks!

**Comment by dgarijo** [comment]
Added in the latest commits.
