### ISSUE TITLE
Add author as property for Hypotheses, LOI and TLOI

### ISSUE THREAD

**Issue by hvarg** [KnowledgeCaptureAndDiscovery/DISK-Ontologies#3]
We need a property to store the author of the hypotheses, LOI, and TLOI.

Something like `:author` should work.

**Comment by dgarijo** [comment]
Author: Person who created the described resource (line of inquiry, LOI, etc.)
Domain: Hypothesis, LOI, TLOI
Range: Person

Person Class
properties: name, email.

@haripriyad252 to add these 3 properties and 1 class.
