### ISSUE TITLE
Support for hypothesis questions

### ISSUE THREAD

**Issue by hvarg** [KnowledgeCaptureAndDiscovery/DISK-Ontologies#5]
We want to change the way hypotheses are defined.

Hypothesis link between `disk:Hypothesis` and `disk:LineOfInquiry`.

We need to define a new class `disk:Question` that will capture all the data related to the hypothesis and all posible modifications.

We need the property `disk:hasQuestion` with domain `LOI` and range `Question` to link the new object.

`Question` will also need the following properties:

-  `disk:hasQuestionTemplate` (string) to show a human readable equivalent of the hypothesis.

- `disk:hasQuestionVariable` (QuestionVariable) to store the rules of possible bindings.

For this, we will also need a new class `disk:QuestionVariable` to save constraints of bindings.
This class needs the following properties:

- `disk:variableName` (string) to store the variable name that will be replaced on the QuestionPattern and QuestionTemplate.

- `disk:constraints` (string) to store a query that will return possible values.

**Comment by dgarijo** [comment]
We have integrated these changes in the ontology
