### ISSUE TITLE
Add property on the ontology to anotate the explanation of the data retrieved with the data query

### ISSUE THREAD

**Issue by hvarg** [KnowledgeCaptureAndDiscovery/DISK-Ontologies#9]
We need a new property to finish https://github.com/KnowledgeCaptureAndDiscovery/DISK/issues/60

Something like `disk:explanation` should work.
The domain is LOI and the range is `xsd:string`

**Comment by dgarijo** [comment]
@haripriyad252 Please call it `dataQueryDescription`, which is more accurate, and add it to the ontology

**Comment by dgarijo** [comment]
Addressed by https://github.com/KnowledgeCaptureAndDiscovery/DISK-Ontologies/pull/11
